Add Jest and Playwright test
upleveled/next-js-example-spring-2022 pull request #5
Opened 2022-06-07 08:14 UTC by ProchaLu

Add Jest and Playwright test from the testing lecture

2022-06-07 09:22 UTC, Josehower requested changes

2022-06-07 09:22 UTC, Josehower commented on playwright.config.ts
> +     */
Not sure if we need all these comments here. This should be probably something the students just copy-paste

2022-06-07 09:22 UTC, Josehower commented on playwright.config.ts
> +  /* Run tests in files in parallel */
Not sure if we need all these comments here. see last comment and all the other comments in this file

2022-06-07 09:22 UTC, Josehower commented on tests/navigate.test.ts
> +  ]);
Let's add a comment here explaining when you need to use promise.all and when not. This seems to be a confusing part of playwright to me and probably also for the students

2022-06-07 09:22 UTC, Josehower commented on tests/navigate.test.ts
> +  const fruitsList = await page.$$('[data-test-id^="fruits-page-fruit-"]');
Comment here explaining why we are using page.$$ and not page.locator

2022-06-07 09:22 UTC, Josehower commented on jest.config.js
> +  // if using TypeScript with a baseUrl set to the root directory then you need the below for alias' to work
not sure if we need all these comments here, this seems to be a file the students should just copy-paste. curious about what is the position @karlhorky  on this. I may be wrong onthis

2022-06-07 09:22 UTC, Josehower commented on util/__tests__/cookies.test.js
> +  expect(getParsedCookie(cookie.key)).toStrictEqual(cookie.value);
probably a small quick tip on when to use toStrictEqual over toBe

2022-06-07 09:22 UTC, Josehower commented on util/__tests__/math.test.js
> +  expect(() => sum(1, '2')).toThrow('Pass only numbers!');
small comment here explaining why we need the arrow function. Or a reminder so them don't forget why is this there

2022-06-07 09:26 UTC, karlhorky commented on jest.config.js
> +  // if using TypeScript with a baseUrl set to the root directory then you need the below for alias' to work
we may not need ALL the comments (especially in the Playwright config file), but I would tend to be slightly more "verbose" (wordy) than we usually would be with comments in our own code, because:

1. some settings configuration files can be a bit complicated to understand
2. the comments for the more confusing things may even help us do the lecture in the future

2022-06-07 09:32 UTC, karlhorky commented on .github/workflows/test-playwright.yml
> +          # path: test-results/tests-navigate-navigation-test-chromium/
what is this line here? make sure you have reviewed every line of the PR - no commented code or any normal things that we try to avoid

2022-06-07 11:00 UTC, karlhorky commented on playwright.config.ts
> +  /* Run your local dev server before starting the tests */
Comment style (we use `//`)

2022-06-07 11:06 UTC, karlhorky commented on .github/workflows/test-playwright.yml
> +      - uses: actions/upload-artifact@v3
@ProchaLu make sure these artifacts are working (post back here with a URL of a test run with uploaded artifacts) and have a good name ("my-artifact" is a bit strange for a name)

2022-06-07 11:07 UTC, karlhorky commented on .github/workflows/test-playwright.yml
> +        # Use the official setup-node action (sets up Node.js):
indentation

2022-06-07 13:14 UTC, ProchaLu commented on .github/workflows/test-playwright.yml
> +      - uses: actions/upload-artifact@v3
[55e190f](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/55e190f664baac7c39b42b093ffae6b795706cbc)

2022-06-07 13:14 UTC, ProchaLu commented on playwright.config.ts
> +  timeout: 30 * 1000,
[60f0610](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/60f0610282179af6e32a17bf8e2459c1f012a671)

2022-06-07 13:15 UTC, ProchaLu commented on playwright.config.ts
> +  /* Run your local dev server before starting the tests */
[60f0610](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/60f0610282179af6e32a17bf8e2459c1f012a671)

2022-06-07 13:15 UTC, ProchaLu commented on .github/workflows/test-playwright.yml
> +          # path: test-results/tests-navigate-navigation-test-chromium/
[55e190f](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/55e190f664baac7c39b42b093ffae6b795706cbc)

2022-06-07 13:15 UTC, ProchaLu commented on util/__tests__/math.test.js
> +  expect(() => sum(1, '2')).toThrow('Pass only numbers!');
[6167867](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/61678675f3b3380b5d5a716567e186825e03636f)

2022-06-07 13:16 UTC, ProchaLu commented on util/__tests__/cookies.test.js
> +  expect(getParsedCookie(cookie.key)).toStrictEqual(cookie.value);
[6167867](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/61678675f3b3380b5d5a716567e186825e03636f)

2022-06-07 13:16 UTC, ProchaLu commented on tests/navigate.test.ts
> +  const fruitsList = await page.$$('[data-test-id^="fruits-page-fruit-"]');
[6167867](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/61678675f3b3380b5d5a716567e186825e03636f)

2022-06-07 13:17 UTC, ProchaLu commented on playwright.config.ts
> +     */
[6167867](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/61678675f3b3380b5d5a716567e186825e03636f)

2022-06-07 13:17 UTC, ProchaLu commented on tests/navigate.test.ts
> +  ]);
[6167867](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/61678675f3b3380b5d5a716567e186825e03636f)

2022-06-07 16:00 UTC, Josehower requested changes

2022-06-07 16:00 UTC, Josehower commented on playwright.config.ts
> +  // so you don't have to run your dev server manually.
let's get rid of these comments, these files are for the students to copy-paste mostly. 

I think also these comments are not from us but from are also copy-pasted from a documentation file. if so let's leave a single comment linking to that file. and delete all the others

2022-06-07 16:00 UTC, Josehower commented on playwright.config.ts
> +  // it will retry the whole test suite.
let's get rid of these comments, these files are for the students to copy-paste mostly.

2022-06-07 16:00 UTC, Josehower commented on playwright.config.ts
> +  // Ignore Jest test files
let's get rid of these comments, these files are for the students to copy-paste mostly.

2022-06-07 16:00 UTC, Josehower commented on playwright.config.ts
> +  // contains report for the test run that can be served as a web page.
let's get rid of these comments, these files are for the students to copy-paste mostly.

2022-06-07 16:00 UTC, Josehower commented on playwright.config.ts
> +  // Creates folder for test artifacts such as screenshots, videos, traces, etc.
let's get rid of these comments, these files are for the students to copy-paste mostly.

2022-06-07 16:00 UTC, Josehower commented on tests/navigate.test.ts
> +  const fruitsList = await page.$$('[data-test-id^="fruits-page-fruit-"]');
this doesn't answer why is different from than page locator.  If I understand right page.locator also finds all elements matching the specified selector within the page.

2022-06-07 16:00 UTC, Josehower commented on util/__tests__/cookies.test.js
> +  // Best practice: clean up after test
we as developers understand what clean up after test means, but I am not sure if a student will

2022-06-07 16:00 UTC, Josehower commented on .github/workflows/test-playwright.yml
> +      PGDATABASE: next_js_example_spring_2022
lets add a comment here explaining the students to add their credentials

2022-06-07 16:00 UTC, Josehower commented on jest.config.js
> +  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
delete theese config comments

2022-06-07 16:00 UTC, Josehower commented on tests/navigate.test.ts
> +  const titleLocator = await page.locator('h1');
small comment here telling what page.locator does

2022-06-07 16:00 UTC, Josehower commented on util/__tests__/__snapshots__/dataStructure.test.js.snap
> +exports[`reduces animal favorite foods 1`] = `
small comment here telling what a snapshot is and why and when we want to use this

2022-06-07 16:29 UTC, Josehower commented on util/__tests__/__snapshots__/dataStructure.test.js.snap
> +exports[`reduces animal favorite foods 1`] = `
Karl told me this may cause the snapshit to fail. So then is better don't add any comment here

2022-06-08 07:50 UTC, ProchaLu commented on tests/navigate.test.ts
> +  const fruitsList = await page.$$('[data-test-id^="fruits-page-fruit-"]');
Changed the comment to describe the difference a little bit more
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:50 UTC, ProchaLu commented on jest.config.js
> +  // if using TypeScript with a baseUrl set to the root directory then you need the below for alias' to work
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:54 UTC, ProchaLu commented on playwright.config.ts
> +  // so you don't have to run your dev server manually.
Added a link for the jest and playwright config
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:54 UTC, ProchaLu commented on playwright.config.ts
> +  // it will retry the whole test suite.
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:54 UTC, ProchaLu commented on playwright.config.ts
> +  // Ignore Jest test files
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:54 UTC, ProchaLu commented on playwright.config.ts
> +  // contains report for the test run that can be served as a web page.
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:54 UTC, ProchaLu commented on playwright.config.ts
> +  // Creates folder for test artifacts such as screenshots, videos, traces, etc.
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:55 UTC, ProchaLu commented on .github/workflows/test-playwright.yml
> +      PGDATABASE: next_js_example_spring_2022
Added a comment [03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:55 UTC, ProchaLu commented on jest.config.js
> +  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
[03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 07:55 UTC, ProchaLu commented on tests/navigate.test.ts
> +  const titleLocator = await page.locator('h1');
Added a comment [03b8de5](https://github.com/upleveled/next-js-example-spring-2022/pull/5/commits/03b8de546791451e663c6f1189e7bc45a45a17d5)

2022-06-08 08:21 UTC, Josehower commented on util/__tests__/cookies.test.js
> +// testing a single, small function that is pure
```suggestion
// testing a single, small function that doesn't depend on a library
```

2022-06-08 08:22 UTC, Josehower commented on playwright.config.ts
> +// https://playwright.dev/docs/test-configuration
```suggestion
// config file reference - https://playwright.dev/docs/test-configuration
```

2022-06-08 08:23 UTC, Josehower commented on tests/navigate.test.ts
> +  // page.locator find elements on the page at any moment.
```suggestion
  // page.locator finds elements on the page at any moment
```

2022-06-08 08:24 UTC, Josehower commented on tests/navigate.test.ts
> +  // and and returns an array of their WebElement instances.
```suggestion
  // and returns an array of WebElement instances
```

2022-06-08 08:25 UTC, Josehower commented on util/__tests__/cookies.test.js
> +  // Use .toBe to compare primitive values or to check referential identity of object instances.
```suggestion
  // Use .toBe to compare primitive values or to check referential identity of object instances
```

2022-06-08 08:26 UTC, Josehower commented on util/__tests__/cookies.test.js
> +  // First, make sure that the value is undefined
```suggestion
  // First, make sure that the return value of the function is undefined
```

2022-06-08 08:26 UTC, Josehower commented on util/__tests__/cookies.test.js
> +  // Use .toStrictEqual to test that objects have the same types as well as structure.
```suggestion
  // Use .toStrictEqual to test that objects have the same types as well as structure
```

2022-06-08 08:46 UTC, Josehower commented on .github/workflows/test-playwright.yml
> +    runs-on: ubuntu-latest # or macos-latest, windows-latest
```suggestion
    runs-on: ubuntu-latest 
    # or macos-latest, windows-latest
```

2022-06-08 08:57 UTC, merged